# Generated by Django 3.1.7 on 2021-03-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
