# Generated by Django 3.1.7 on 2021-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0002_score_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
    ]
