# Generated by Django 3.1.7 on 2021-03-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0005_auto_20210302_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='abc.jpg', upload_to='question_pics'),
        ),
    ]
