# Generated by Django 3.1.7 on 2021-03-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0007_auto_20210302_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.TextField(default='none.jpg'),
        ),
    ]
