# Generated by Django 3.1.7 on 2021-03-07 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0008_auto_20210305_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='last_submit',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 16, 11, 40, 553861, tzinfo=utc)),
        ),
    ]
