# Generated by Django 3.1.6 on 2021-05-28 11:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0009_auto_20210307_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='picked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='score',
            name='last_submit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='score',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
