# Generated by Django 2.1.5 on 2022-03-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epsilon', '0011_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifeline', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='lifelin1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='lifeline2',
            field=models.IntegerField(default=0),
        ),
    ]
